AllCops:
  TargetRubyVersion: 2.5
  DisplayStyleGuide: true
  DisplayCopNames: true
  Exclude:
    - .gems/**/*
    - bin/**/*
    - config/**/*
    - db/**/*
    - log/**/*
    - public/**/*
    - tmp/**/*
    - vendor/**/*
    - lib/tasks/**/*
    - spec/rails_helper.rb
    - spec/spec_helper.rb
    - config.ru
    - Guardfile
    - Rakefile
    - node_modules/**/*
    - app/queries/**/*

Bundler/OrderedGems:
  Enabled: false

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/SpaceInsidePercentLiteralDelimiters:
  Enabled: false

Layout/SpaceAroundOperators:
  EnforcedStyleForExponentOperator: space

Layout/LineLength:
  Enabled: false

Lint/MissingSuper:
  Exclude:
    - 'app/services/**/*'

Naming/AccessorMethodName:
  Enabled: false

Naming/PredicateName:
  Enabled: false

Style/AndOr:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/MutableConstant:
  Enabled: true

Style/Semicolon:
  AllowAsExpressionSeparator: true

Style/SingleLineBlockParams:
  Enabled: false

Style/HashTransformKeys:
  Enabled: false

Style/HashTransformValues:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/NumericLiterals:
  MinDigits: 7

Style/WordArray:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Metrics/AbcSize:
  Max: 50

Metrics/BlockNesting:
  Max: 4

Metrics/BlockLength:
  Max: 65
  Exclude:
    - 'spec/**/*'

Metrics/ClassLength:
  Max: 300

Metrics/ModuleLength:
  Max: 300

Metrics/MethodLength:
  Max: 50

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Max: 10

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/LineLength:
  Enabled: false

Lint/DuplicateBranch: # (new in 1.3)
  Enabled: true

Lint/DuplicateRegexpCharacterClassElement: # (new in 1.1)
  Enabled: true

Lint/EmptyBlock: # (new in 1.1)
  Enabled: true

Lint/EmptyClass: # (new in 1.3)
  Enabled: true

Lint/NoReturnInBeginEndBlocks: # (new in 1.2)
  Enabled: true

Lint/ToEnumArguments: # (new in 1.1)
  Enabled: true

Lint/UnmodifiedReduceAccumulator: # (new in 1.1)
  Enabled: true

Style/ArgumentsForwarding: # (new in 1.1)
  Enabled: true

Style/CollectionCompact: # (new in 1.2)
  Enabled: true

Style/DocumentDynamicEvalDefinition: # (new in 1.1)
  Enabled: true

Style/NegatedIfElseCondition: # (new in 1.2)
  Enabled: true

Style/NilLambda: # (new in 1.3)
  Enabled: true

Style/RedundantArgument: # (new in 1.4)
  Enabled: true

Style/SwapValues: # (new in 1.1)
  Enabled: true

Performance/HashEachMethods:
  Enabled: false
