version: '3'

x-webservice: &webservice
  build:
    context: .
  hostname: localhost
  networks:
    - proxy
  environment:
    FORCE_COLOR: 1
    DEBUG_COLORS: 'true'
    TERM: xterm-256color
    COLORTERM: truecolor
  restart: on-failure:3
  tty: true

services:
  bilingo:
    <<: *webservice
    image: wgmin/bilingo
    container_name: bilingo
    ports:
      - 3001:3000
    env_file:
      - .env
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.bilingo.rule=Host(`bilingo.mtech.id.vn`)
      - traefik.http.routers.bilingo.entrypoints=websecure
      - traefik.http.routers.bilingo.tls=true
      - traefik.http.routers.bilingo.tls.certresolver=letsencrypt
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/up']
      interval: 200s
      timeout: 200s
      retries: 5

  bilingo-sidekiq:
    <<: *webservice
    image: wgmin/bilingo-sidekiq
    container_name: bilingo-sidekiq
    command: bundle exec sidekiq
    depends_on:
      - bilingo

networks:
  proxy:
    external: true
