version: 2.1
orbs:
  ruby: circleci/ruby@2.0.1
  coveralls: coveralls/coveralls@2.2.1
jobs:
  test-ruby:
    docker:
      - image: cimg/ruby:3.3.0-node
        environment:
          BILINGO_DATABASE_URL: postgresql://bilingo@localhost/bilingo_test

      - image: circleci/postgres:9.5-alpine
        environment:
          POSTGRES_USER: bilingo
          POSTGRES_DB: bilingo_test

    environment:
      RAILS_ENV: test

    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Database setup
          command: bundle exec rake db:test:prepare
      - run:
          name: rspec test
          command: bundle exec rspec
      - coveralls/upload:
          path_to_lcov: ./coverage/lcov/project.lcov
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: deploy
          command: '#e.g. ./deploy.sh'
workflows:
  build-and-test:
    jobs:
      - test-ruby
    # - deploy:
    #     requires:
    #       - test-ruby
